export type CatalogItem = {
  id: string;
  slug: string;
  kind: "animal" | "supply";
  name: string;
  category: string;
  species?: "Hamster" | "Kelinci";
  breed?: string;
  sex?: "Jantan" | "Betina";
  age?: string;
  code?: string;
  temperament?: string;
  price: number;
  stock: number;
  status: "Tersedia" | "Direservasi" | "Stok menipis" | "Stok habis" | "Terjual";
  image: string;
  description: string;
  featured?: boolean;
  weightGrams?: number;
  dimensions?: string;
};

export const animals: CatalogItem[] = [
  {
    id: "a1",
    slug: "mochi-syrian",
    kind: "animal",
    name: "Mochi",
    category: "Hamster",
    species: "Hamster",
    breed: "Syrian",
    sex: "Jantan",
    age: "2 bulan",
    code: "HM-SY-018",
    temperament: "Aktif & penasaran",
    price: 185000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/33914110/pexels-photo-33914110/free-photo-of-adorable-golden-syrian-hamster-portrait-close-up.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Syrian jantan usia 2 bulan. Aktif, makannya lahap, dan sudah cukup santai saat dipegang pelan.",
    featured: true,
  },
  {
    id: "a2",
    slug: "boba-campbell",
    kind: "animal",
    name: "Boba",
    category: "Hamster",
    species: "Hamster",
    breed: "Campbell",
    sex: "Betina",
    age: "1,5 bulan",
    code: "HM-CP-011",
    temperament: "Tenang",
    price: 150000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/3362698/pexels-photo-3362698.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Campbell betina usia 1,5 bulan. Geraknya tenang dan tidak gampang kaget saat didekati pelan.",
    featured: true,
  },
  {
    id: "a3",
    slug: "yuki-winter-white",
    kind: "animal",
    name: "Yuki",
    category: "Hamster",
    species: "Hamster",
    breed: "Winter White",
    sex: "Betina",
    age: "2 bulan",
    code: "HM-WW-019",
    temperament: "Ramah",
    price: 165000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1738485974110-4756f78bfa6a?auto=format&fit=crop&w=1200&q=82",
    description: "Winter White betina usia 2 bulan. Aktif di malam hari dan cukup cepat beradaptasi dengan kandang baru.",
  },
  {
    id: "a4",
    slug: "pippin-roborovski",
    kind: "animal",
    name: "Pippin",
    category: "Hamster",
    species: "Hamster",
    breed: "Roborovski",
    sex: "Jantan",
    age: "1 bulan",
    code: "HM-RB-024",
    temperament: "Lincah",
    price: 175000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347108338-eea3ebf3d6a8?auto=format&fit=crop&w=1200&q=82",
    description: "Roborovski jantan usia 1 bulan. Kecil, cepat, dan lebih cocok dilihat bermain daripada sering digendong.",
  },
  {
    id: "a5",
    slug: "luna-holland-lop",
    kind: "animal",
    name: "Luna",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Holland Lop",
    sex: "Betina",
    age: "3 bulan",
    code: "KL-HL-024",
    temperament: "Tenang & ramah",
    price: 450000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1591382386627-349b692688ff?auto=format&fit=crop&w=1200&q=82",
    description: "Holland Lop betina usia 3 bulan. Tenang, suka dielus pelan, dan sudah terbiasa makan hay.",
    featured: true,
  },
  {
    id: "a6",
    slug: "nibbles-netherland-dwarf",
    kind: "animal",
    name: "Nibbles",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Netherland Dwarf",
    sex: "Jantan",
    age: "2,5 bulan",
    code: "KL-ND-007",
    temperament: "Penasaran",
    price: 375000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1559214369-a6b1d7919865?auto=format&fit=crop&w=1200&q=82",
    description: "Netherland Dwarf jantan usia 2,5 bulan. Penasaran dan senang keliling area bermain.",
    featured: true,
  },
  {
    id: "a7",
    slug: "oreo-mini-rex",
    kind: "animal",
    name: "Oreo",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Mini Rex",
    sex: "Betina",
    age: "4 bulan",
    code: "KL-MR-019",
    temperament: "Lembut",
    price: 525000,
    stock: 1,
    status: "Direservasi",
    image: "https://images.pexels.com/photos/20049445/pexels-photo-20049445/free-photo-of-close-up-of-a-pet-dwarf-rabbit.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Mini Rex betina usia 4 bulan. Bulunya halus, makannya baik, dan perlu waktu sebentar untuk akrab.",
  },
  {
    id: "a8",
    slug: "theo-lionhead",
    kind: "animal",
    name: "Theo",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Lionhead",
    sex: "Jantan",
    age: "3 bulan",
    code: "KL-LH-009",
    temperament: "Ramah",
    price: 495000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1452857297128-d9c29adba80b?auto=format&fit=crop&w=1200&q=82",
    description: "Lionhead jantan usia 3 bulan. Ramah, aktif, dan perlu rutin disisir supaya bulunya tidak kusut.",
  },
  {
    id: "a9",
    slug: "kuma-syrian-long-hair",
    kind: "animal",
    name: "Kuma",
    category: "Hamster",
    species: "Hamster",
    breed: "Syrian Long Hair",
    sex: "Jantan",
    age: "2,5 bulan",
    code: "HM-SL-031",
    temperament: "Santai & mudah penasaran",
    price: 225000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/33914110/pexels-photo-33914110/free-photo-of-adorable-golden-syrian-hamster-portrait-close-up.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Syrian Long Hair jantan dengan bulu tebal. Sudah terbiasa makan seed mix dan nyaman saat didekati pelan.",
    featured: true,
  },
  {
    id: "a10",
    slug: "choco-syrian",
    kind: "animal",
    name: "Choco",
    category: "Hamster",
    species: "Hamster",
    breed: "Syrian",
    sex: "Betina",
    age: "2 bulan",
    code: "HM-SY-032",
    temperament: "Aktif malam hari",
    price: 195000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/3362698/pexels-photo-3362698.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Syrian betina usia 2 bulan. Aktif menjelang malam, suka menggali bedding, dan makannya teratur.",
  },
  {
    id: "a11",
    slug: "miso-campbell",
    kind: "animal",
    name: "Miso",
    category: "Hamster",
    species: "Hamster",
    breed: "Campbell",
    sex: "Jantan",
    age: "1,5 bulan",
    code: "HM-CP-033",
    temperament: "Gesit",
    price: 155000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1738485974110-4756f78bfa6a?auto=format&fit=crop&w=1200&q=82",
    description: "Campbell jantan yang gesit dan suka menjelajah lorong. Cocok untuk kandang dwarf dengan banyak enrichment.",
  },
  {
    id: "a12",
    slug: "pompom-winter-white",
    kind: "animal",
    name: "Pompom",
    category: "Hamster",
    species: "Hamster",
    breed: "Winter White",
    sex: "Jantan",
    age: "2 bulan",
    code: "HM-WW-034",
    temperament: "Tenang",
    price: 170000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/33914110/pexels-photo-33914110/free-photo-of-adorable-golden-syrian-hamster-portrait-close-up.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Winter White jantan yang relatif tenang. Sudah terbiasa memakai sand bath dan botol minum.",
  },
  {
    id: "a13",
    slug: "sesame-roborovski",
    kind: "animal",
    name: "Sesame",
    category: "Hamster",
    species: "Hamster",
    breed: "Roborovski",
    sex: "Betina",
    age: "1,5 bulan",
    code: "HM-RB-035",
    temperament: "Cepat & aktif",
    price: 180000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/3362698/pexels-photo-3362698.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Roborovski betina yang sangat aktif. Lebih nyaman diamati saat bermain daripada sering dipegang.",
  },
  {
    id: "a14",
    slug: "taro-campbell",
    kind: "animal",
    name: "Taro",
    category: "Hamster",
    species: "Hamster",
    breed: "Campbell",
    sex: "Betina",
    age: "2 bulan",
    code: "HM-CP-036",
    temperament: "Penasaran",
    price: 160000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1738485974110-4756f78bfa6a?auto=format&fit=crop&w=1200&q=82",
    description: "Campbell betina yang penasaran dengan lingkungan baru. Makan baik dan aktif memakai roda lari.",
  },
  {
    id: "a15",
    slug: "peanut-syrian",
    kind: "animal",
    name: "Peanut",
    category: "Hamster",
    species: "Hamster",
    breed: "Syrian",
    sex: "Jantan",
    age: "3 bulan",
    code: "HM-SY-037",
    temperament: "Kalem",
    price: 210000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/33914110/pexels-photo-33914110/free-photo-of-adorable-golden-syrian-hamster-portrait-close-up.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Syrian jantan usia 3 bulan dengan gerak yang kalem. Suka bersembunyi di multichamber saat siang.",
  },
  {
    id: "a16",
    slug: "sora-winter-white",
    kind: "animal",
    name: "Sora",
    category: "Hamster",
    species: "Hamster",
    breed: "Winter White",
    sex: "Betina",
    age: "1,5 bulan",
    code: "HM-WW-038",
    temperament: "Ramah",
    price: 168000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/3362698/pexels-photo-3362698.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Winter White betina yang cepat mendekat saat diberi camilan. Tetap perlu adaptasi pelan di kandang baru.",
  },
];

export const supplies: CatalogItem[] = [
  {
    id: "p1",
    slug: "wide-hamster-habitat",
    kind: "supply",
    name: "Wide Hamster Habitat",
    category: "Habitat & Kandang",
    price: 1250000,
    stock: 6,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Habitat 80 × 50 × 40 cm dengan ventilasi luas dan dasar dalam untuk bedding.",
    weightGrams: 12500,
    dimensions: "80 × 50 × 40 cm",
    featured: true,
  },
  {
    id: "p2",
    slug: "rabbit-exercise-pen",
    kind: "supply",
    name: "Rabbit Exercise Pen",
    category: "Habitat & Kandang",
    price: 850000,
    stock: 4,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Pagar delapan panel untuk membatasi area bermain kelinci di dalam rumah.",
    weightGrams: 9200,
    dimensions: "8 panel × 75 cm",
    featured: true,
  },
  {
    id: "p3",
    slug: "natural-seed-mix",
    kind: "supply",
    name: "Natural Seed Mix",
    category: "Pakan & Hay",
    price: 85000,
    stock: 18,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Campuran biji dan pelet seimbang untuk hamster dewasa, kemasan 1 kg.",
    weightGrams: 1000,
  },
  {
    id: "p4",
    slug: "timothy-hay-premium",
    kind: "supply",
    name: "Timothy Hay Premium",
    category: "Pakan & Hay",
    price: 95000,
    stock: 5,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Timothy hay kering kemasan 1 kg untuk pakan harian kelinci dewasa.",
    weightGrams: 1000,
    featured: true,
  },
  {
    id: "p5",
    slug: "aspen-bedding",
    kind: "supply",
    name: "Aspen Bedding Bebas Debu",
    category: "Alas & Litter",
    price: 110000,
    stock: 9,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Alas aspen rendah debu dengan daya serap baik, kemasan 16 liter.",
    weightGrams: 3200,
  },
  {
    id: "p6",
    slug: "ceramic-bowl",
    kind: "supply",
    name: "Mangkok Keramik",
    category: "Tempat Makan & Minum",
    price: 75000,
    stock: 12,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/34789308/pexels-photo-34789308/free-photo-of-charming-handcrafted-ceramic-animal-bowls.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Mangkok keramik berat dan stabil, mudah dibersihkan, diameter 12 cm.",
    weightGrams: 420,
  },
  {
    id: "p7",
    slug: "natural-chew-set",
    kind: "supply",
    name: "Natural Chew & Play Set",
    category: "Mainan & Enrichment",
    price: 125000,
    stock: 15,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/10884424/pexels-photo-10884424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Isi enam mainan kayu untuk dikunyah dan dimainkan hamster atau kelinci.",
    weightGrams: 350,
  },
  {
    id: "p8",
    slug: "pet-carrier-medium",
    kind: "supply",
    name: "Pet Carrier Medium",
    category: "Carrier & Perjalanan",
    price: 425000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Carrier ukuran 48 × 31 × 32 cm dengan lubang udara dan pintu pengunci.",
    weightGrams: 2400,
    dimensions: "48 × 31 × 32 cm",
  },
  {
    id: "p9",
    slug: "glass-habitat-100",
    kind: "supply",
    name: "Glass Habitat 100",
    category: "Habitat & Kandang",
    price: 2150000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Habitat kaca ekstra lega dengan tutup mesh, akses depan, dan ruang bedding sedalam 25 cm.",
    weightGrams: 28500,
    dimensions: "100 × 50 × 50 cm",
  },
  {
    id: "p10",
    slug: "bin-cage-120l",
    kind: "supply",
    name: "Bin Cage Ventilasi 120L",
    category: "Habitat & Kandang",
    price: 495000,
    stock: 8,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Kandang plastik 120 liter dengan panel jaring besar dan pengunci di bagian atas.",
    weightGrams: 4800,
    dimensions: "75 × 48 × 42 cm",
  },
  {
    id: "p11",
    slug: "rabbit-indoor-condo",
    kind: "supply",
    name: "Rabbit Indoor Condo",
    category: "Habitat & Kandang",
    price: 1680000,
    stock: 2,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Kandang kelinci dua tingkat dengan ramp, alas lepas-pasang, dan ruang tidur tertutup.",
    weightGrams: 21000,
    dimensions: "120 × 60 × 92 cm",
  },
  {
    id: "p12",
    slug: "hamster-complete-pellet",
    kind: "supply",
    name: "Hamster Complete Pellet",
    category: "Pakan & Hay",
    price: 72000,
    stock: 24,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Pelet lengkap tanpa pewarna dengan protein seimbang untuk hamster Syrian dan dwarf, 750 gram.",
    weightGrams: 750,
  },
  {
    id: "p13",
    slug: "rabbit-adult-pellet",
    kind: "supply",
    name: "Rabbit Adult Pellet",
    category: "Pakan & Hay",
    price: 128000,
    stock: 16,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Pelet tinggi serat berbasis timothy untuk kelinci dewasa, kemasan kedap udara 1,5 kg.",
    weightGrams: 1500,
  },
  {
    id: "p14",
    slug: "orchard-grass-hay",
    kind: "supply",
    name: "Orchard Grass Hay",
    category: "Pakan & Hay",
    price: 105000,
    stock: 14,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Hay bertekstur lembut dan aromatik sebagai variasi serat harian kelinci, 1 kg.",
    weightGrams: 1000,
  },
  {
    id: "p15",
    slug: "alfalfa-hay-junior",
    kind: "supply",
    name: "Alfalfa Hay Junior",
    category: "Pakan & Hay",
    price: 89000,
    stock: 10,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Hay alfalfa kaya nutrisi untuk kelinci muda sesuai porsi yang direkomendasikan, 800 gram.",
    weightGrams: 800,
  },
  {
    id: "p16",
    slug: "botanical-forage-mix",
    kind: "supply",
    name: "Botanical Forage Mix",
    category: "Pakan & Hay",
    price: 59000,
    stock: 20,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Campuran bunga, daun, dan herba kering untuk ditabur di area makan.",
    weightGrams: 180,
  },
  {
    id: "p17",
    slug: "paper-bedding-cloud",
    kind: "supply",
    name: "Paper Bedding Cloud",
    category: "Alas & Litter",
    price: 135000,
    stock: 13,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Bedding kertas lembut tanpa pewangi, mengembang hingga 30 liter dan nyaman untuk membuat sarang.",
    weightGrams: 2600,
  },
  {
    id: "p18",
    slug: "tofu-litter-natural",
    kind: "supply",
    name: "Tofu Litter Natural",
    category: "Alas & Litter",
    price: 98000,
    stock: 11,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Litter tofu rendah debu dan cepat menggumpal untuk area toilet kelinci, 6 liter.",
    weightGrams: 2500,
  },
  {
    id: "p19",
    slug: "silent-cork-wheel",
    kind: "supply",
    name: "Silent Cork Wheel 28",
    category: "Mainan & Enrichment",
    price: 385000,
    stock: 7,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/10884424/pexels-photo-10884424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Roda lari beralas gabus dengan bearing senyap dan diameter aman untuk hamster Syrian.",
    weightGrams: 1250,
    dimensions: "Diameter 28 cm",
  },
  {
    id: "p20",
    slug: "multichamber-hideout",
    kind: "supply",
    name: "Multichamber Hideout",
    category: "Mainan & Enrichment",
    price: 275000,
    stock: 6,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/10884424/pexels-photo-10884424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Rumah kayu tiga ruang dengan atap lepas untuk meniru lorong sarang alami hamster.",
    weightGrams: 1350,
    dimensions: "31 × 22 × 12 cm",
  },
  {
    id: "p21",
    slug: "glass-water-bottle",
    kind: "supply",
    name: "Botol Minum Kaca 250 ml",
    category: "Tempat Makan & Minum",
    price: 89000,
    stock: 19,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/34789308/pexels-photo-34789308/free-photo-of-charming-handcrafted-ceramic-animal-bowls.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Botol kaca tahan gigitan dengan indikator isi dan dudukan kawat yang stabil.",
    weightGrams: 380,
  },
  {
    id: "p22",
    slug: "oak-hay-rack",
    kind: "supply",
    name: "Oak Hay Rack",
    category: "Tempat Makan & Minum",
    price: 235000,
    stock: 5,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/34789308/pexels-photo-34789308/free-photo-of-charming-handcrafted-ceramic-animal-bowls.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Rak hay berdiri dengan bukaan lebar agar hay tetap bersih dan mudah dijangkau kelinci.",
    weightGrams: 1600,
  },
  {
    id: "p23",
    slug: "rabbit-grooming-kit",
    kind: "supply",
    name: "Rabbit Grooming Kit",
    category: "Perawatan & Grooming",
    price: 245000,
    stock: 9,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1591382386627-349b692688ff?auto=format&fit=crop&w=1200&q=82",
    description: "Set sisir lembut, slicker kecil, pemotong kuku, dan kantong penyimpanan untuk perawatan rutin.",
    weightGrams: 620,
  },
  {
    id: "p24",
    slug: "granite-cooling-tile",
    kind: "supply",
    name: "Granite Cooling Tile",
    category: "Perawatan & Grooming",
    price: 165000,
    stock: 12,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Lempeng granit 30 × 20 cm untuk tempat berbaring saat cuaca hangat.",
    weightGrams: 2800,
    dimensions: "30 × 20 cm",
  },
  {
    id: "p25",
    slug: "travel-carrier-small",
    kind: "supply",
    name: "Travel Carrier Small",
    category: "Carrier & Perjalanan",
    price: 265000,
    stock: 8,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Carrier kompak dengan ventilasi menyeluruh untuk hamster dan perjalanan singkat ke dokter hewan.",
    weightGrams: 1100,
    dimensions: "32 × 21 × 23 cm",
  },
  {
    id: "p26",
    slug: "hamster-starter-kit",
    kind: "supply",
    name: "Hamster Starter Kit",
    category: "Starter Kit",
    price: 1890000,
    stock: 4,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Isi kandang lebar, roda 28 cm, rumah kecil, mangkok, bedding, dan pakan awal.",
    weightGrams: 18500,
    dimensions: "Paket 6 item",
    featured: true,
  },
  {
    id: "p27",
    slug: "rabbit-home-starter-kit",
    kind: "supply",
    name: "Rabbit Home Starter Kit",
    category: "Starter Kit",
    price: 2350000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Isi pagar bermain, kotak litter, rak hay, mangkok, alat grooming, pelet, dan timothy hay.",
    weightGrams: 17800,
    dimensions: "Paket 7 item",
    featured: true,
  },
  {
    id: "p28",
    slug: "kandang-hamster-full-akrilik-100",
    kind: "supply",
    name: "Kandang Hamster Full Akrilik 100×50×50 cm",
    category: "Habitat & Kandang",
    price: 1485000,
    stock: 5,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi kandang akrilik ukuran 100 × 50 × 50 cm dari supplier. Cocok untuk set-up hamster luas; pilihan packing kayu tersedia di halaman supplier.",
    weightGrams: 9800,
    dimensions: "100 × 50 × 50 cm",
    featured: true,
  },
  {
    id: "p29",
    slug: "bucatstate-acrylic-metal-frame",
    kind: "supply",
    name: "BUCATSTATE Acrylic Metal Frame 100/120 cm",
    category: "Habitat & Kandang",
    price: 5880000,
    stock: 2,
    status: "Stok menipis",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi habitat BUCATSTATE frame metal berukuran 100/120 cm. Cocok untuk set-up premium dengan ruang enrichment lebih banyak.",
    weightGrams: 34000,
    dimensions: "100/120 cm",
  },
  {
    id: "p30",
    slug: "kandang-hamster-akrilik-2-tingkat-80",
    kind: "supply",
    name: "Kandang Hamster Akrilik 2 Tingkat 80×60×100 cm",
    category: "Habitat & Kandang",
    price: 2000000,
    stock: 7,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Referensi kandang akrilik dua tingkat 80 × 60 × 100 cm dari supplier. Siapkan set-up dan ventilasi sebelum hewan dipindahkan.",
    weightGrams: 7200,
    dimensions: "80 × 60 × 100 cm",
  },
  {
    id: "p31",
    slug: "kandang-hamster-akrilik-2-tingkat-100",
    kind: "supply",
    name: "Kandang Hamster Akrilik 2 Tingkat 100×50×100 cm",
    category: "Habitat & Kandang",
    price: 2640000,
    stock: 4,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi kandang akrilik dua tingkat 100 × 50 × 100 cm dari supplier untuk set-up koleksi atau habitat besar.",
    weightGrams: 22000,
    dimensions: "100 × 50 × 100 cm",
  },
  {
    id: "p32",
    slug: "kandang-hamster-akrilik-100-40-30",
    kind: "supply",
    name: "Kandang Hamster Akrilik 100×40×30 cm",
    category: "Habitat & Kandang",
    price: 1050000,
    stock: 10,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Referensi kandang akrilik 100 × 40 × 30 cm dari supplier. Gunakan hanya setelah ventilasi dan kelengkapan habitat siap.",
    weightGrams: 3900,
    dimensions: "100 × 40 × 30 cm",
  },
  {
    id: "p33",
    slug: "teraterarium-hamster-akrilik-kayu",
    kind: "supply",
    name: "TeraTerarium Hamster Akrilik Kayu Trapesium",
    category: "Habitat & Kandang",
    price: 395000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi terarium akrilik-kayu bergaya trapesium dari supplier. Pilihan ringkas untuk display dengan perlengkapan dwarf hamster.",
    weightGrams: 26500,
    dimensions: "Lihat variasi supplier",
  },
  {
    id: "p34",
    slug: "corn-cob-bedding-1l",
    kind: "supply",
    name: "Corn Cob Bedding 1L",
    category: "Alas & Litter",
    price: 11900,
    stock: 18,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Referensi alas kandang corn cob 1 liter dari supplier. Bahan kering untuk lapisan kandang kecil; ganti rutin agar tetap bersih.",
    weightGrams: 600,
  },
  {
    id: "p35",
    slug: "cocopeat-hamster-bedding-steril-50g",
    kind: "supply",
    name: "Cocopeat Hamster Bedding Steril 50 g",
    category: "Alas & Litter",
    price: 5000,
    stock: 30,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi cocopeat steril 50 gram dari supplier untuk campuran media gali. Pastikan tetap kering sebelum dipakai.",
    weightGrams: 50,
  },
  {
    id: "p36",
    slug: "seedlicious-seedmix-hamster",
    kind: "supply",
    name: "SEEDLICIOUS Seedmix Hamster",
    category: "Pakan & Hay",
    price: 25500,
    stock: 24,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi seed mix untuk hamster dwarf maupun Syrian dari supplier. Sajikan sesuai porsi dan lengkapi dengan air minum bersih.",
    weightGrams: 500,
  },
  {
    id: "p37",
    slug: "tissue-bedding-premium-hello-syrian",
    kind: "supply",
    name: "Tissue Bedding Premium Hello Syrian",
    category: "Alas & Litter",
    price: 29999,
    stock: 20,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi tissue bedding premium dari supplier untuk topping sarang. Gunakan bahan kering dan tanpa pewangi menyengat.",
    weightGrams: 250,
  },
  {
    id: "p38",
    slug: "ham-spa-natural-sand-bath",
    kind: "supply",
    name: "HAM SPA Natural Sand Bath",
    category: "Alas & Litter",
    price: 20000,
    stock: 25,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi pasir mandi bebas pewangi dari supplier. Sediakan wadah terpisah dan ganti bila mulai lembap atau kotor.",
    weightGrams: 500,
  },
  {
    id: "p39",
    slug: "hamsf-bunny-rabbit-food-1kg",
    kind: "supply",
    name: "HAMSF Bunny Rabbit Food 1 kg",
    category: "Pakan & Hay",
    price: 33999,
    stock: 16,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Referensi pakan pelet kelinci 1 kg dari supplier. Tetap jadikan hay sebagai sumber serat utama sesuai kebutuhan kelinci.",
    weightGrams: 1000,
  },
  {
    id: "p40",
    slug: "paper-bedding-hamppiness",
    kind: "supply",
    name: "Paper Bedding by Hamppiness",
    category: "Alas & Litter",
    price: 60000,
    stock: 14,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi paper bedding dari supplier. Mengembang sebagai lapisan nyaman untuk membuat sarang dan perlu diganti berkala.",
    weightGrams: 1000,
  },
  {
    id: "p41",
    slug: "pasir-alas-hamster-jolly-1kg",
    kind: "supply",
    name: "Pasir Alas Hamster Jolly 1 kg",
    category: "Alas & Litter",
    price: 9900,
    stock: 30,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Referensi pasir alas hamster 1 kg dari supplier. Simpan dalam kondisi kering dan gunakan pada wadah yang mudah dibersihkan.",
    weightGrams: 1000,
  },
];

export const allItems = [...animals, ...supplies];

export const formatRupiah = (value: number) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(value);
