export type CatalogItem = {
  id: string;
  slug: string;
  kind: "animal" | "supply";
  name: string;
  category: string;
  species?: "Hamster" | "Kelinci";
  breed?: string;
  sex?: "Jantan" | "Betina";
  age?: string;
  code?: string;
  temperament?: string;
  price: number;
  stock: number;
  status: "Tersedia" | "Direservasi" | "Stok menipis" | "Stok habis" | "Terjual";
  image: string;
  description: string;
  featured?: boolean;
  weightGrams?: number;
  dimensions?: string;
};

export const animals: CatalogItem[] = [
  {
    id: "a1",
    slug: "mochi-syrian",
    kind: "animal",
    name: "Mochi",
    category: "Hamster",
    species: "Hamster",
    breed: "Syrian",
    sex: "Jantan",
    age: "2 bulan",
    code: "HM-SY-018",
    temperament: "Aktif & penasaran",
    price: 185000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/33914110/pexels-photo-33914110/free-photo-of-adorable-golden-syrian-hamster-portrait-close-up.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Syrian muda yang aktif, nyaman dipegang, dan sudah terbiasa dengan rutinitas makan teratur.",
    featured: true,
  },
  {
    id: "a2",
    slug: "boba-campbell",
    kind: "animal",
    name: "Boba",
    category: "Hamster",
    species: "Hamster",
    breed: "Campbell",
    sex: "Betina",
    age: "1,5 bulan",
    code: "HM-CP-011",
    temperament: "Tenang",
    price: 150000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/3362698/pexels-photo-3362698.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Campbell betina dengan karakter tenang dan responsif terhadap interaksi perlahan.",
    featured: true,
  },
  {
    id: "a3",
    slug: "yuki-winter-white",
    kind: "animal",
    name: "Yuki",
    category: "Hamster",
    species: "Hamster",
    breed: "Winter White",
    sex: "Betina",
    age: "2 bulan",
    code: "HM-WW-019",
    temperament: "Ramah",
    price: 165000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1738485974110-4756f78bfa6a?auto=format&fit=crop&w=1200&q=82",
    description: "Winter White berbulu lembut, mudah beradaptasi, dan cocok untuk pemilik yang telaten.",
  },
  {
    id: "a4",
    slug: "pippin-roborovski",
    kind: "animal",
    name: "Pippin",
    category: "Hamster",
    species: "Hamster",
    breed: "Roborovski",
    sex: "Jantan",
    age: "1 bulan",
    code: "HM-RB-024",
    temperament: "Lincah",
    price: 175000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347108338-eea3ebf3d6a8?auto=format&fit=crop&w=1200&q=82",
    description: "Roborovski berukuran mungil dan sangat lincah, ideal untuk diamati di habitat yang luas.",
  },
  {
    id: "a5",
    slug: "luna-holland-lop",
    kind: "animal",
    name: "Luna",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Holland Lop",
    sex: "Betina",
    age: "3 bulan",
    code: "KL-HL-024",
    temperament: "Tenang & ramah",
    price: 450000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1591382386627-349b692688ff?auto=format&fit=crop&w=1200&q=82",
    description: "Holland Lop betina yang lembut, terbiasa disentuh, dan menyukai suasana yang tenang.",
    featured: true,
  },
  {
    id: "a6",
    slug: "nibbles-netherland-dwarf",
    kind: "animal",
    name: "Nibbles",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Netherland Dwarf",
    sex: "Jantan",
    age: "2,5 bulan",
    code: "KL-ND-007",
    temperament: "Penasaran",
    price: 375000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1559214369-a6b1d7919865?auto=format&fit=crop&w=1200&q=82",
    description: "Netherland Dwarf yang penasaran dan aktif mengeksplorasi area bermainnya.",
    featured: true,
  },
  {
    id: "a7",
    slug: "oreo-mini-rex",
    kind: "animal",
    name: "Oreo",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Mini Rex",
    sex: "Betina",
    age: "4 bulan",
    code: "KL-MR-019",
    temperament: "Lembut",
    price: 525000,
    stock: 1,
    status: "Direservasi",
    image: "https://images.pexels.com/photos/20049445/pexels-photo-20049445/free-photo-of-close-up-of-a-pet-dwarf-rabbit.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Mini Rex dengan bulu beludru yang sehat dan karakter lembut setelah beradaptasi.",
  },
  {
    id: "a8",
    slug: "theo-lionhead",
    kind: "animal",
    name: "Theo",
    category: "Kelinci",
    species: "Kelinci",
    breed: "Lionhead",
    sex: "Jantan",
    age: "3 bulan",
    code: "KL-LH-009",
    temperament: "Ramah",
    price: 495000,
    stock: 1,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1452857297128-d9c29adba80b?auto=format&fit=crop&w=1200&q=82",
    description: "Lionhead muda dengan bulu sehat dan karakter sosial yang menyenangkan.",
  },
];

export const supplies: CatalogItem[] = [
  {
    id: "p1",
    slug: "wide-hamster-habitat",
    kind: "supply",
    name: "Wide Hamster Habitat",
    category: "Habitat & Kandang",
    price: 1250000,
    stock: 6,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Habitat 80 × 50 × 40 cm dengan ventilasi luas dan dasar dalam untuk bedding.",
    weightGrams: 12500,
    dimensions: "80 × 50 × 40 cm",
    featured: true,
  },
  {
    id: "p2",
    slug: "rabbit-exercise-pen",
    kind: "supply",
    name: "Rabbit Exercise Pen",
    category: "Habitat & Kandang",
    price: 850000,
    stock: 4,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Pagar latihan modular delapan panel untuk area bermain kelinci yang aman.",
    weightGrams: 9200,
    dimensions: "8 panel × 75 cm",
    featured: true,
  },
  {
    id: "p3",
    slug: "natural-seed-mix",
    kind: "supply",
    name: "Natural Seed Mix",
    category: "Pakan & Hay",
    price: 85000,
    stock: 18,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Campuran biji dan pelet seimbang untuk hamster dewasa, kemasan 1 kg.",
    weightGrams: 1000,
  },
  {
    id: "p4",
    slug: "timothy-hay-premium",
    kind: "supply",
    name: "Timothy Hay Premium",
    category: "Pakan & Hay",
    price: 95000,
    stock: 5,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Hay kering berkualitas untuk membantu pencernaan dan kesehatan gigi kelinci.",
    weightGrams: 1000,
    featured: true,
  },
  {
    id: "p5",
    slug: "aspen-bedding",
    kind: "supply",
    name: "Aspen Bedding Bebas Debu",
    category: "Alas & Litter",
    price: 110000,
    stock: 9,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Alas aspen rendah debu dengan daya serap baik, kemasan 16 liter.",
    weightGrams: 3200,
  },
  {
    id: "p6",
    slug: "ceramic-bowl",
    kind: "supply",
    name: "Mangkok Keramik",
    category: "Tempat Makan & Minum",
    price: 75000,
    stock: 12,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/34789308/pexels-photo-34789308/free-photo-of-charming-handcrafted-ceramic-animal-bowls.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Mangkok keramik berat dan stabil, mudah dibersihkan, diameter 12 cm.",
    weightGrams: 420,
  },
  {
    id: "p7",
    slug: "natural-chew-set",
    kind: "supply",
    name: "Natural Chew & Play Set",
    category: "Mainan & Enrichment",
    price: 125000,
    stock: 15,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/10884424/pexels-photo-10884424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Enam mainan kunyah kayu alami untuk stimulasi dan perawatan gigi.",
    weightGrams: 350,
  },
  {
    id: "p8",
    slug: "pet-carrier-medium",
    kind: "supply",
    name: "Pet Carrier Medium",
    category: "Carrier & Perjalanan",
    price: 425000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Carrier berventilasi dengan pintu kokoh untuk perjalanan singkat dan pengambilan.",
    weightGrams: 2400,
    dimensions: "48 × 31 × 32 cm",
  },
  {
    id: "p9",
    slug: "glass-habitat-100",
    kind: "supply",
    name: "Glass Habitat 100",
    category: "Habitat & Kandang",
    price: 2150000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Habitat kaca ekstra lega dengan tutup mesh, akses depan, dan ruang bedding sedalam 25 cm.",
    weightGrams: 28500,
    dimensions: "100 × 50 × 50 cm",
  },
  {
    id: "p10",
    slug: "bin-cage-120l",
    kind: "supply",
    name: "Bin Cage Ventilasi 120L",
    category: "Habitat & Kandang",
    price: 495000,
    stock: 8,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Kandang ringan dengan panel mesh besar dan pengunci aman untuk habitat hamster pemula.",
    weightGrams: 4800,
    dimensions: "75 × 48 × 42 cm",
  },
  {
    id: "p11",
    slug: "rabbit-indoor-condo",
    kind: "supply",
    name: "Rabbit Indoor Condo",
    category: "Habitat & Kandang",
    price: 1680000,
    stock: 2,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Rumah kelinci indoor dua tingkat dengan ramp landai, alas mudah dilepas, dan area istirahat tertutup.",
    weightGrams: 21000,
    dimensions: "120 × 60 × 92 cm",
  },
  {
    id: "p12",
    slug: "hamster-complete-pellet",
    kind: "supply",
    name: "Hamster Complete Pellet",
    category: "Pakan & Hay",
    price: 72000,
    stock: 24,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Pelet lengkap tanpa pewarna dengan protein seimbang untuk hamster Syrian dan dwarf, 750 gram.",
    weightGrams: 750,
  },
  {
    id: "p13",
    slug: "rabbit-adult-pellet",
    kind: "supply",
    name: "Rabbit Adult Pellet",
    category: "Pakan & Hay",
    price: 128000,
    stock: 16,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Pelet tinggi serat berbasis timothy untuk kelinci dewasa, kemasan kedap udara 1,5 kg.",
    weightGrams: 1500,
  },
  {
    id: "p14",
    slug: "orchard-grass-hay",
    kind: "supply",
    name: "Orchard Grass Hay",
    category: "Pakan & Hay",
    price: 105000,
    stock: 14,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Hay bertekstur lembut dan aromatik sebagai variasi serat harian kelinci, 1 kg.",
    weightGrams: 1000,
  },
  {
    id: "p15",
    slug: "alfalfa-hay-junior",
    kind: "supply",
    name: "Alfalfa Hay Junior",
    category: "Pakan & Hay",
    price: 89000,
    stock: 10,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Hay alfalfa kaya nutrisi untuk kelinci muda sesuai porsi yang direkomendasikan, 800 gram.",
    weightGrams: 800,
  },
  {
    id: "p16",
    slug: "botanical-forage-mix",
    kind: "supply",
    name: "Botanical Forage Mix",
    category: "Pakan & Hay",
    price: 59000,
    stock: 20,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1778347088164-b60ccf347dce?auto=format&fit=crop&w=1200&q=82",
    description: "Campuran bunga, daun, dan herba kering untuk aktivitas mencari makan yang lebih natural.",
    weightGrams: 180,
  },
  {
    id: "p17",
    slug: "paper-bedding-cloud",
    kind: "supply",
    name: "Paper Bedding Cloud",
    category: "Alas & Litter",
    price: 135000,
    stock: 13,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Bedding kertas lembut tanpa pewangi, mengembang hingga 30 liter dan nyaman untuk membuat sarang.",
    weightGrams: 2600,
  },
  {
    id: "p18",
    slug: "tofu-litter-natural",
    kind: "supply",
    name: "Tofu Litter Natural",
    category: "Alas & Litter",
    price: 98000,
    stock: 11,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Litter tofu rendah debu dan cepat menggumpal untuk area toilet kelinci, 6 liter.",
    weightGrams: 2500,
  },
  {
    id: "p19",
    slug: "silent-cork-wheel",
    kind: "supply",
    name: "Silent Cork Wheel 28",
    category: "Mainan & Enrichment",
    price: 385000,
    stock: 7,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/10884424/pexels-photo-10884424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Roda lari beralas gabus dengan bearing senyap dan diameter aman untuk hamster Syrian.",
    weightGrams: 1250,
    dimensions: "Diameter 28 cm",
  },
  {
    id: "p20",
    slug: "multichamber-hideout",
    kind: "supply",
    name: "Multichamber Hideout",
    category: "Mainan & Enrichment",
    price: 275000,
    stock: 6,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/10884424/pexels-photo-10884424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Rumah kayu tiga ruang dengan atap lepas untuk meniru lorong sarang alami hamster.",
    weightGrams: 1350,
    dimensions: "31 × 22 × 12 cm",
  },
  {
    id: "p21",
    slug: "glass-water-bottle",
    kind: "supply",
    name: "Botol Minum Kaca 250 ml",
    category: "Tempat Makan & Minum",
    price: 89000,
    stock: 19,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/34789308/pexels-photo-34789308/free-photo-of-charming-handcrafted-ceramic-animal-bowls.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Botol kaca tahan gigitan dengan indikator isi dan dudukan kawat yang stabil.",
    weightGrams: 380,
  },
  {
    id: "p22",
    slug: "oak-hay-rack",
    kind: "supply",
    name: "Oak Hay Rack",
    category: "Tempat Makan & Minum",
    price: 235000,
    stock: 5,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/34789308/pexels-photo-34789308/free-photo-of-charming-handcrafted-ceramic-animal-bowls.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Rak hay berdiri dengan bukaan lebar agar hay tetap bersih dan mudah dijangkau kelinci.",
    weightGrams: 1600,
  },
  {
    id: "p23",
    slug: "rabbit-grooming-kit",
    kind: "supply",
    name: "Rabbit Grooming Kit",
    category: "Perawatan & Grooming",
    price: 245000,
    stock: 9,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1591382386627-349b692688ff?auto=format&fit=crop&w=1200&q=82",
    description: "Set sisir lembut, slicker kecil, pemotong kuku, dan kantong penyimpanan untuk perawatan rutin.",
    weightGrams: 620,
  },
  {
    id: "p24",
    slug: "granite-cooling-tile",
    kind: "supply",
    name: "Granite Cooling Tile",
    category: "Perawatan & Grooming",
    price: 165000,
    stock: 12,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1657076761228-bdb21cf0bc7c?auto=format&fit=crop&w=1200&q=82",
    description: "Lempeng granit halus yang membantu hewan beristirahat lebih nyaman saat cuaca hangat.",
    weightGrams: 2800,
    dimensions: "30 × 20 cm",
  },
  {
    id: "p25",
    slug: "travel-carrier-small",
    kind: "supply",
    name: "Travel Carrier Small",
    category: "Carrier & Perjalanan",
    price: 265000,
    stock: 8,
    status: "Tersedia",
    image: "https://images.pexels.com/photos/9769857/pexels-photo-9769857.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Carrier kompak dengan ventilasi menyeluruh untuk hamster dan perjalanan singkat ke dokter hewan.",
    weightGrams: 1100,
    dimensions: "32 × 21 × 23 cm",
  },
  {
    id: "p26",
    slug: "hamster-starter-kit",
    kind: "supply",
    name: "Hamster Starter Kit",
    category: "Starter Kit",
    price: 1890000,
    stock: 4,
    status: "Tersedia",
    image: "https://images.unsplash.com/photo-1754921506553-9f0be3d8e87e?auto=format&fit=crop&w=1200&q=82",
    description: "Paket habitat lebar, wheel 28 cm, hideout, mangkok, bedding, dan pakan untuk minggu pertama.",
    weightGrams: 18500,
    dimensions: "Paket 6 item",
    featured: true,
  },
  {
    id: "p27",
    slug: "rabbit-home-starter-kit",
    kind: "supply",
    name: "Rabbit Home Starter Kit",
    category: "Starter Kit",
    price: 2350000,
    stock: 3,
    status: "Stok menipis",
    image: "https://images.pexels.com/photos/29210008/pexels-photo-29210008/free-photo-of-adorable-white-and-black-rabbits-in-hay.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Paket exercise pen, litter tray, hay rack, mangkok, grooming kit, pellet, dan timothy hay.",
    weightGrams: 17800,
    dimensions: "Paket 7 item",
    featured: true,
  },
];

export const allItems = [...animals, ...supplies];

export const formatRupiah = (value: number) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(value);
